(function(){
'use strict';
const view=document.querySelector('#adminView'),title=document.querySelector('#sectionTitle'),nav=document.querySelector('#adminNav');
const sections=[['dashboard','◈','Dashboard'],['users','👥','Benutzer'],['roles','🛡','Rollen & Rechte'],['content','📁','Inhalte'],['packages','📦','Prompt-Pakete'],['premium','💎','Premium'],['exclusive','🔒','Exklusiv'],['songCreator','🎵','Song Creator'],['coverCreator','🖼','Cover Creator'],['ai','✦','KI'],['shop','🛍','Shop'],['statistics','📊','Statistiken'],['logs','📜','Logs'],['settings','⚙','Einstellungen'],['backup','💾','Backup']];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=message=>{const el=document.querySelector('#adminToast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)};
const download=(name,text)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
const metric=(label,value,kind='')=>`<article class="admin-card metric ${kind}"><span>${esc(label)}</span><strong>${esc(value)}</strong></article>`;
const panel=(heading,content)=>`<section class="admin-panel"><h2>${heading}</h2>${content}</section>`;
const field=(label,name,value='',type='text')=>`<label>${label}<input type="${type}" name="${name}" value="${esc(value)}"></label>`;
function renderDashboard(){const x=AdminStatistics.get(),s=AdminCore.snapshot();return `<div class="admin-grid">${metric('Benutzer',x.users)}${metric('Aktiv',x.active)}${metric('Premium',x.premium,'gold')}${metric('Gesperrt',x.banned,'pink')}${metric('Songs',x.songs)}${metric('Cover',x.covers)}${metric('Prompt-Pakete',x.packages)}${metric('App-Version',s.settings.appVersion)}</div>${panel('Letzte Admin-Aktionen',logsTable(s.logs.slice(0,8)))}${panel('Beliebte Inhalte',`<p>Themen: ${esc(x.popularThemes.join(', ')||'Noch keine Nutzungsdaten')}</p><p>Genres: ${esc(x.popularGenres.join(', ')||'Noch keine Nutzungsdaten')}</p>`)}`}
function usersTable(users){return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Benutzer</th><th>Rolle</th><th>Status</th><th>Nutzung</th><th>Aktionen</th></tr></thead><tbody>${users.map(u=>`<tr><td><strong>${esc(u.username)}</strong><br><small>${esc(u.email)}</small></td><td>${esc(u.role)} ${u.premium?'<span class="badge gold">Premium</span>':''}</td><td>${u.banned?'<span class="badge danger">Gesperrt</span>':'<span class="badge">Aktiv</span>'}${u.requiresPasswordReset?'<br><small>Passwortwechsel offen</small>':''}</td><td>${u.songs} Songs · ${u.covers} Cover</td><td class="row-actions">${u.role==='Owner'?'<span class="badge gold">Geschützt</span>':`<button class="ac-button secondary" data-user-edit="${esc(u.username)}">Bearbeiten</button><button class="ac-button secondary" data-user-premium="${esc(u.username)}">💎</button><button class="ac-button secondary" data-user-ban="${esc(u.username)}">${u.banned?'Entsperren':'Sperren'}</button><button class="ac-button secondary" data-user-reset="${esc(u.username)}">Passwort-Reset</button><button class="ac-button danger" data-user-delete="${esc(u.username)}">Löschen</button>`}</td></tr>`).join('')}</tbody></table></div>`}
function renderUsers(){return `<div class="admin-toolbar"><input id="userSearch" placeholder="Benutzer suchen …"><select id="userFilter"><option value="">Alle Rollen</option>${AdminRoles.list().map(r=>`<option>${esc(r.name)}</option>`).join('')}</select><button class="ac-button secondary" id="exportUsers">Exportieren</button></div><div id="userResults">${usersTable(AdminUsers.list().sort((a,b)=>a.username.localeCompare(b.username,'de')))}</div>`}
function renderRoles(){return `<div class="admin-toolbar"><input id="newRoleName" placeholder="Neue Rolle"><button class="ac-button" id="newRole">Rolle erstellen</button></div><div class="admin-grid">${AdminRoles.list().map(r=>`<article class="admin-card"><h3>${esc(r.name)} ${r.locked?'<span class="badge gold">System</span>':''}</h3><div class="permission-grid">${AdminRoles.permissions.map(p=>`<label><input type="checkbox" data-role-perm="${esc(r.id)}" value="${p}" ${r.permissions.includes(p)?'checked':''} ${r.name==='Owner'?'disabled':''}> ${p}</label>`).join('')}</div>${!r.locked&&!AdminCore.BASE_ROLES.includes(r.name)?`<button class="ac-button danger" data-role-delete="${esc(r.id)}">Rolle löschen</button>`:''}</article>`).join('')}</div>`}
function renderContent(){const cats=AdminContent.categories(),key=sessionStorage.getItem('admin.content.category')||cats[0]?.key||'',c=cats.find(x=>x.key===key)||cats[0];return `<div class="admin-toolbar"><select id="contentCategory">${cats.map(x=>`<option value="${x.key}" ${x.key===c?.key?'selected':''}>${esc(x.label)}</option>`).join('')}</select><input id="contentName" placeholder="Neuer Eintrag"><select id="contentTier"><option value="normal">Normal</option><option value="premium">Premium</option><option value="exclusive">Exklusiv</option></select><button class="ac-button" id="contentAdd">Erstellen</button><button class="ac-button secondary" id="contentSort">Alphabetisch</button></div><p class="section-note">Kategorie → Eintrag. Die bestehende SongAdmin-Datenquelle bleibt erhalten.</p><div class="content-list">${(c?.items||[]).map(i=>`<article class="content-item ${i.active?'':'inactive'}"><strong>${esc(i.name)}</strong><p><span class="badge ${i.tier==='premium'?'gold':''}">${esc(i.tier)}</span> · ${i.active?'Aktiv':'Inaktiv'}</p><div class="row-actions"><button class="ac-button secondary" data-content-toggle="${i.id}">☑</button><button class="ac-button secondary" data-content-edit="${i.id}">Umbenennen</button><button class="ac-button secondary" data-content-copy="${i.id}">Duplizieren</button><button class="ac-button danger" data-content-delete="${i.id}">Löschen</button></div></article>`).join('')}</div>`}
function renderPackages(){const s=AdminCore.snapshot();return `<div class="admin-toolbar"><input id="packageName" placeholder="Paketname"><button class="ac-button" id="packageAdd">Paket erstellen</button><button class="ac-button secondary" id="packageExport">Exportieren</button></div><div class="admin-grid">${s.packages.map(p=>`<article class="admin-card"><h3>${esc(p.name)}</h3><p>${p.premium?'💎 Premium':''} ${p.exclusive?'🔒 Exklusiv':''}</p><button class="ac-button secondary" data-package-copy="${p.id}">Duplizieren</button> <button class="ac-button danger" data-package-delete="${p.id}">Löschen</button></article>`).join('')||'<p class="empty">Noch keine Prompt-Pakete.</p>'}</div>`}
function configForm(section,data){const inputs=Object.entries(data).filter(([,v])=>['string','number','boolean'].includes(typeof v)).map(([k,v])=>typeof v==='boolean'?`<label><input type="checkbox" name="${k}" ${v?'checked':''}> ${esc(k)}</label>`:field(k,k,v,typeof v==='number'?'number':'text')).join('');return `<form class="admin-panel admin-form" data-config="${section}">${inputs}<label class="wide">JSON-Erweiterungen<textarea name="__json" rows="9">${esc(JSON.stringify(data,null,2))}</textarea></label><div class="wide"><button class="ac-button" type="submit">Einstellungen speichern</button></div></form>`}
function shopAdminForm(){const s=AdminShop.get();return `<form class="admin-panel admin-form" id="centralShopForm">${field('Monatspreis','monthlyPrice',s.monthlyPrice,'number')}${field('Jahrespreis','yearlyPrice',s.yearlyPrice,'number')}${field('Währung','currency',s.currency)}${field('Testphase in Tagen','trialDays',s.trialDays,'number')}${field('Beschreibung','description',s.description)}${field('Aktionspreis','promotionalPrice',s.promotionalPrice??'','number')}${field('Rabatt in Prozent','discountPercent',s.discountPercent,'number')}${field('Beginn der Aktion','promotionStart',s.promotionStart,'date')}${field('Ende der Aktion','promotionEnd',s.promotionEnd,'date')}<label><input type="checkbox" name="shopEnabled" ${s.shopEnabled?'checked':''}> Shop aktiv</label><label><input type="checkbox" name="monthlyEnabled" ${s.monthlyEnabled?'checked':''}> Monatsabo aktiv</label><label><input type="checkbox" name="yearlyEnabled" ${s.yearlyEnabled?'checked':''}> Jahresabo aktiv</label><label class="wide">Sichtbare Premium-Vorteile<textarea name="benefits" rows="7">${esc((s.benefits||[]).join('\n'))}</textarea></label><div class="wide"><button class="ac-button" type="submit">Shop-Einstellungen speichern</button></div></form>`}function renderPremium(){return `<p class="section-note">Premium-Limits und zentrale Shop-Preise.</p>${configForm('premium',AdminPremium.get())}${shopAdminForm()}`}function renderExclusive(){return configForm('exclusive',AdminPremium.exclusive())}function renderSongCreator(){return configForm('songCreator',AdminCore.snapshot().songCreator)}function renderCoverCreator(){return configForm('coverCreator',AdminCore.snapshot().coverCreator)}function renderAI(){return `<p class="section-note">Keine API-Schlüssel werden im Frontend gespeichert.</p>${configForm('ai',AdminCore.snapshot().ai)}`}function renderShop(){return `<p class="section-note">Die hier gespeicherten Werte erscheinen sofort im Premium-Shop. Es wird keine Zahlung ausgelöst.</p>${shopAdminForm()}`}function renderSettings(){return configForm('settings',AdminCore.snapshot().settings)}
function renderStatistics(){const x=AdminStatistics.get();return `<div class="admin-grid">${Object.entries(x).filter(([,v])=>typeof v==='number').map(([k,v])=>metric(k,v)).join('')}</div>${panel('Nutzung nach Zeitraum','<p class="empty">Wird aus zukünftigen Nutzungsereignissen automatisch aufgebaut.</p>')}`}
function logsTable(logs){return `<div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Zeit</th><th>Benutzer</th><th>Aktion</th><th>Ziel</th><th>Details</th></tr></thead><tbody>${logs.map(l=>`<tr><td>${esc(new Date(l.timestamp).toLocaleString('de-DE'))}</td><td>${esc(l.user)}</td><td>${esc(l.action)}</td><td>${esc(l.target)}</td><td>${esc(l.details)}</td></tr>`).join('')}</tbody></table></div>`}function renderLogs(){return `<div class="admin-toolbar"><button class="ac-button secondary" id="logExport">Logs exportieren</button></div>${logsTable(AdminLogs.list())}`}
function renderBackup(){return `<div class="admin-grid"><article class="admin-card"><h2>JSON exportieren</h2><p>Vollständiger Admin-Datenstand inklusive Migrationssicherung.</p><button class="ac-button" id="backupExport">Exportieren</button></article><article class="admin-card"><h2>Backup erstellen</h2><p>Lokalen Wiederherstellungspunkt erzeugen.</p><button class="ac-button" id="backupCreate">Backup erstellen</button></article><article class="admin-card"><h2>Wiederherstellen</h2><p>Der Owner bleibt bei jedem Restore geschützt.</p><button class="ac-button danger" id="backupRestore">JSON importieren</button></article></div>${panel('Lokale Backups',AdminBackup.list().map(b=>`<p>${esc(new Date(b.timestamp).toLocaleString('de-DE'))} · ${esc(b.id)}</p>`).join('')||'<p class="empty">Noch keine Backups.</p>')}`}
const renders={dashboard:renderDashboard,users:renderUsers,roles:renderRoles,content:renderContent,packages:renderPackages,premium:renderPremium,exclusive:renderExclusive,songCreator:renderSongCreator,coverCreator:renderCoverCreator,ai:renderAI,shop:renderShop,statistics:renderStatistics,logs:renderLogs,settings:renderSettings,backup:renderBackup};
let active=location.hash.slice(1)||'dashboard';if(!renders[active])active='dashboard';
function render(){const item=sections.find(s=>s[0]===active);title.textContent=item[2];view.innerHTML=renders[active]();nav.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.section===active));bind();}
function bind(){
 const search=document.querySelector('#userSearch'),filter=document.querySelector('#userFilter');const refreshUsers=()=>{document.querySelector('#userResults').innerHTML=usersTable(AdminUsers.search(search?.value||'').filter(u=>!filter?.value||u.role===filter.value).sort((a,b)=>a.username.localeCompare(b.username,'de')))};search?.addEventListener('input',refreshUsers);filter?.addEventListener('change',refreshUsers);document.querySelector('#exportUsers')?.addEventListener('click',()=>download('benutzer.json',AdminUsers.export()));
 document.querySelector('#newRole')?.addEventListener('click',()=>act(()=>AdminRoles.create(document.querySelector('#newRoleName').value),true));document.querySelectorAll('[data-role-perm]').forEach(cb=>cb.addEventListener('change',()=>{const role=AdminRoles.list().find(r=>r.id===cb.dataset.rolePerm),permissions=[...document.querySelectorAll(`[data-role-perm="${CSS.escape(role.id)}"]:checked`)].map(x=>x.value);act(()=>AdminRoles.update(role.id,{permissions}))}));
 document.querySelector('#contentCategory')?.addEventListener('change',e=>{sessionStorage.setItem('admin.content.category',e.target.value);render()});document.querySelector('#contentAdd')?.addEventListener('click',()=>{const key=document.querySelector('#contentCategory').value,name=document.querySelector('#contentName').value,tier=document.querySelector('#contentTier').value;act(()=>AdminContent.add(key,{name,tier,active:true,roles:[...SongAdmin.ROLES]}),true)});
 document.querySelector('#packageAdd')?.addEventListener('click',()=>act(()=>AdminCore.addPackage({name:document.querySelector('#packageName').value||'Neues Paket'}),true));document.querySelector('#packageExport')?.addEventListener('click',()=>download('prompt-pakete.json',JSON.stringify(AdminCore.snapshot().packages,null,2)));document.querySelector('#logExport')?.addEventListener('click',()=>download('admin-logs.json',AdminLogs.export()));
 document.querySelectorAll('[data-config]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();act(()=>{let value=JSON.parse(form.elements.__json.value);[...form.elements].forEach(el=>{if(!el.name||el.name==='__json')return;value[el.name]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value});AdminCore.setSection(form.dataset.config,value)})}));document.querySelector('#centralShopForm')?.addEventListener('submit',e=>{e.preventDefault();act(()=>{const f=e.currentTarget,s=AdminShop.get();['monthlyPrice','yearlyPrice','trialDays','promotionalPrice','discountPercent'].forEach(k=>s[k]=f.elements[k].value===''?null:Number(f.elements[k].value));['currency','description','promotionStart','promotionEnd'].forEach(k=>s[k]=f.elements[k].value);['shopEnabled','monthlyEnabled','yearlyEnabled'].forEach(k=>s[k]=f.elements[k].checked);s.benefits=f.elements.benefits.value.split('\n').map(x=>x.trim()).filter(Boolean);AdminShop.save(s)},true)});
 document.querySelector('#backupExport')?.addEventListener('click',()=>download(`song-creator-backup-${Date.now()}.json`,AdminBackup.export()));document.querySelector('#backupCreate')?.addEventListener('click',()=>act(()=>AdminBackup.create(),true));document.querySelector('#backupRestore')?.addEventListener('click',()=>document.querySelector('#backupImport').click());
}
function act(fn,rerender=false){try{fn();toast('Änderung gespeichert.');if(rerender)render()}catch(e){toast(e.message)}}
view.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;const name=el.dataset.userEdit||el.dataset.userPremium||el.dataset.userBan||el.dataset.userReset||el.dataset.userDelete;if(name){const u=AdminUsers.list().find(x=>x.username===name);if(el.dataset.userEdit){const email=prompt('E-Mail',u.email),role=prompt('Rolle',u.role);if(email!==null&&role!==null)act(()=>AdminUsers.update(name,{email,role}),true)}else if(el.dataset.userPremium)act(()=>AdminUsers.premium(name,!u.premium),true);else if(el.dataset.userBan)act(()=>AdminUsers.ban(name,!u.banned),true);else if(el.dataset.userReset)act(()=>AdminUsers.resetPassword(name),true);else if(confirm('Benutzer wirklich löschen?'))act(()=>AdminUsers.remove(name),true);return}if(el.dataset.roleDelete&&confirm('Rolle löschen?'))act(()=>AdminRoles.remove(el.dataset.roleDelete),true);const key=document.querySelector('#contentCategory')?.value,id=el.dataset.contentToggle||el.dataset.contentEdit||el.dataset.contentCopy||el.dataset.contentDelete;if(id&&key){const item=SongAdmin.category(key).items.find(x=>x.id===id);if(el.dataset.contentToggle)act(()=>AdminContent.update(key,id,{...item,active:!item.active}),true);else if(el.dataset.contentEdit){const name=prompt('Neuer Name',item.name);if(name)act(()=>AdminContent.update(key,id,{...item,name}),true)}else if(el.dataset.contentCopy)act(()=>AdminContent.duplicate(key,item),true);else if(confirm('Eintrag löschen?'))act(()=>AdminContent.remove(key,id),true)}if(el.dataset.packageCopy){const p=AdminCore.snapshot().packages.find(x=>x.id===el.dataset.packageCopy);act(()=>AdminCore.addPackage({...p,id:undefined,name:`${p.name} Kopie`}),true)}if(el.dataset.packageDelete&&confirm('Paket löschen?'))act(()=>AdminCore.removePackage(el.dataset.packageDelete),true)});
document.querySelector('#backupImport').addEventListener('change',async e=>{try{const data=JSON.parse(await e.target.files[0].text());if(confirm('Backup wirklich wiederherstellen? Bestehender Admin-Datenstand wird ersetzt; Legacy-Daten und Owner bleiben geschützt.')){AdminBackup.restore(data);toast('Backup wiederhergestellt.');render()}}catch(err){toast(`Import fehlgeschlagen: ${err.message}`)}e.target.value=''});
nav.innerHTML=sections.map(([id,icon,label])=>`<button class="nav-item" data-section="${id}"><span>${icon}</span><span class="nav-label">${label}</span></button>`).join('');nav.addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(!b)return;active=b.dataset.section;location.hash=active;document.body.classList.remove('nav-open');render()});document.querySelector('#sidebarToggle').addEventListener('click',()=>document.body.classList.toggle('collapsed'));document.querySelector('#mobileNav').addEventListener('click',()=>document.body.classList.toggle('nav-open'));document.querySelector('#adminName').textContent=AdminCore.currentUser();document.querySelector('#adminRole').textContent=AdminCore.currentRole();render();
}());
